### ISSUE TITLE
Create FormSubmitButton component

### ISSUE THREAD

**Issue by Kneesal** [JesusFilm/core#5668]
**Objective:**
Create a FormSubmitButton component that will be used to submit form data from text input fields.

**Requirements:**

* Create a new FormSubmitButton component or extend the existing ButtonBlock component
* Ensure the button is visually distinct as a submit button
* Support customization of button text
* Implement proper accessibility attributes for form submission
* Position the button appropriately in relation to form fields

**Implementation Details:**

* Create a FormSubmitButton component that extends or works with the existing ButtonBlock
* Implement the following features:
  * Custom button text
  * Visual styling to indicate it's a submit button
  * Proper ARIA attributes for accessibility
  * Loading state during submission
* Ensure the button is properly associated with form fields

**Technical Approach:**

```tsx
// Example implementation
interface FormSubmitButtonProps {
  text?: string;
  isSubmitting?: boolean;
  onClick: () => void;
  // other props
}

const FormSubmitButton: React.FC<FormSubmitButtonProps> = ({
  text = 'Submit',
  isSubmitting = false,
  onClick,
  // other props
}) => {
  return (
    <button
      type="submit"
      className="form-submit-button"
      onClick={onClick}
      disabled={isSubmitting}
      aria-busy={isSubmitting}
    >
      {isSubmitting ? 'Submitting...' : text}
    </button>
  );
};

// Usage with ButtonBlock
const ButtonBlock: React.FC<ButtonBlockProps> = ({
  block,
  // other props
}) => {
  const {
    text,
    noSubmit = false,
    // other props
  } = block;
  
  const handleClick = () => {
    if (noSubmit) {
      // Regular button behavior
    } else {
      // Submit form behavior
    }
  };
  
  return noSubmit ? (
    <button
      className="regular-button"
      onClick={handleClick}
      // other props
    >
      {text}
    </button>
  ) : (
    <FormSubmitButton
      text={text}
      onClick={handleClick}
      // other props
    />
  );
};
```

**CSS Styling:**

```css
.form-submit-button {
  background-color: #5e6ad2;
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  font-weight: 500;
  margin-top: 1rem;
}

.form-submit-button:hover {
  background-color: #4a54b8;
}

.form-submit-button:disabled {
  background-color: #a0a8e4;
  cursor: not-allowed;
}
```

**Testing Considerations:**

* Verify that the button renders correctly
* Test button click behavior
* Test with various button text values
* Ensure proper accessibility for screen readers and keyboard navigation
* Test loading/submitting state
* Verify styling is consistent with design guidelines
* Test responsiveness on different screen sizes
