### ISSUE TITLE
Add submit button customization options

### ISSUE THREAD

**Issue by Kneesal** [JesusFilm/core#5671]
**Objective:**
Implement customization options for the submit button to allow users to tailor the button appearance and behavior to their needs.

**Requirements:**

* Allow customization of button text
* Support styling options (colors, size, etc.)
* Enable positioning options relative to form fields
* Maintain accessibility standards with all customizations
* Ensure responsive design with all customizations

**Implementation Details:**

* Extend the ButtonBlock schema to include submit button specific options:
  * `submitButtonText`: Custom text for the submit button (default: "Submit")
  * `submitButtonStyle`: Style options for the submit button
  * `submitButtonPosition`: Position options for the submit button
* Update the ButtonBlock editor UI to include these customization options
* Modify the FormSubmitButton component to apply these customizations

**Technical Approach:**

```tsx
// Extended ButtonBlock schema
interface ButtonBlockSchema extends BaseBlockSchema {
  text: string;
  noSubmit: boolean;
  submitButtonText?: string;
  submitButtonStyle?: {
    backgroundColor?: string;
    textColor?: string;
    size?: 'small' | 'medium' | 'large';
    fullWidth?: boolean;
  };
  submitButtonPosition?: 'left' | 'center' | 'right';
  // other properties
}

// Updated FormSubmitButton component
const FormSubmitButton: React.FC<FormSubmitButtonProps> = ({
  text = 'Submit',
  style = {},
  position = 'center',
  isSubmitting = false,
  onClick,
  // other props
}) => {
  // Generate class names based on position and style
  const buttonClasses = classNames(
    'form-submit-button',
    `form-submit-button--${position}`,
    {
      'form-submit-button--small': style.size === 'small',
      'form-submit-button--medium': style.size === 'medium' || !style.size,
      'form-submit-button--large': style.size === 'large',
      'form-submit-button--full-width': style.fullWidth
    }
  );
  
  // Generate inline styles for custom colors
  const buttonStyles = {
    backgroundColor: style.backgroundColor,
    color: style.textColor
  };
  
  return (
    <div className={`form-submit-container form-submit-container--${position}`}>
      <button
        type="submit"
        className={buttonClasses}
        style={buttonStyles}
        onClick={onClick}
        disabled={isSubmitting}
        aria-busy={isSubmitting}
      >
        {isSubmitting ? 'Submitting...' : text}
      </button>
    </div>
  );
};

// Usage in ButtonBlock
const ButtonBlock: React.FC<ButtonBlockProps> = ({
  block,
  // other props
}) => {
  const {
    text,
    noSubmit = false,
    submitButtonText,
    submitButtonStyle,
    submitButtonPosition,
    // other props
  } = block;
  
  // Rest of component implementation
  
  return noSubmit ? (
    // Regular button rendering
  ) : (
    <FormSubmitButton
      text={submitButtonText || text}
      style={submitButtonStyle}
      position={submitButtonPosition}
      onClick={handleSubmit}
      // other props
    />
  );
};
```

**CSS Styling:**

```css
.form-submit-container {
  margin-top: 1rem;
  width: 100%;
}

.form-submit-container--left {
  text-align: left;
}

.form-submit-container--center {
  text-align: center;
}

.form-submit-container--right {
  text-align: right;
}

.form-submit-button {
  background-color: #5e6ad2;
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  font-weight: 500;
}

.form-submit-button--small {
  font-size: 0.85rem;
  padding: 0.3rem 0.8rem;
}

.form-submit-button--large {
  font-size: 1.2rem;
  padding: 0.7rem 1.5rem;
}

.form-submit-button--full-width {
  width: 100%;
}
```

**Testing Considerations:**

* Verify that all customization options work correctly
* Test with various combinations of customization options
* Ensure proper accessibility with all customizations
* Test responsiveness on different screen sizes
* Verify that customizations persist when saved and reloaded
* Test with extreme values for customization options
