### ISSUE TITLE
Create error message display system

### ISSUE THREAD

**Issue by Kneesal** [JesusFilm/core#5677]
**Objective:**
Create a comprehensive error message display system for form validation to provide clear feedback to users about validation errors.

**Requirements:**

* Implement a consistent system for displaying validation error messages
* Support different types of validation errors (required, format, etc.)
* Ensure error messages are visually distinct and noticeable
* Maintain accessibility standards for error messages
* Support both field-level and form-level error messages

**Implementation Details:**

* Create a reusable error message component
* Implement styling for error messages that is consistent with the design system
* Ensure proper ARIA attributes for accessibility
* Support different error message types and severities
* Implement proper positioning of error messages relative to form fields

**Technical Approach:**

```tsx
// Error message component
interface ErrorMessageProps {
  message: string;
  id?: string;
  severity?: 'error' | 'warning' | 'info';
}

const ErrorMessage: React.FC<ErrorMessageProps> = ({
  message,
  id,
  severity = 'error'
}) => {
  if (!message) return null;
  
  const className = `validation-message validation-message--${severity}`;
  
  return (
    <div 
      id={id}
      className={className}
      role="alert"
    >
      {severity === 'error' && (
        <span className="validation-icon" aria-hidden="true">
          ⚠️
        </span>
      )}
      <span className="validation-text">{message}</span>
    </div>
  );
};

// Form-level error message component
interface FormErrorMessageProps {
  errors: ValidationError[];
}

const FormErrorMessage: React.FC<FormErrorMessageProps> = ({ errors }) => {
  if (!errors || errors.length === 0) return null;
  
  return (
    <div className="form-validation-summary" role="alert" aria-live="assertive">
      <h3 className="validation-summary-title">Please correct the following errors:</h3>
      <ul className="validation-summary-list">
        {errors.map((error, index) => (
          <li key={index} className="validation-summary-item">
            <a 
              href={`#text-input-${error.id}`}
              onClick={(e) => {
                e.preventDefault();
                const element = document.getElementById(`text-input-${error.id}`);
                if (element) {
                  element.focus();
                }
              }}
            >
              {error.fieldName}: {error.errorMessage}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
};

// Usage in TextInputBlock
const TextInputBlock: React.FC<TextInputBlockProps> = ({ 
  block, 
  onChange,
  validationError,
  ...props 
}) => {
  // Component implementation
  
  const errorId = `error-${block.id}`;
  
  return (
    <div className="text-input-block">
      {/* Label and input implementation */}
      {validationError && (
        <ErrorMessage
          id={errorId}
          message={validationError}
          severity="error"
        />
      )}
    </div>
  );
};

// Usage in form component
const FormComponent: React.FC = () => {
  const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);
  
  // Form implementation
  
  return (
    <div className="form-container">
      {validationErrors.length > 0 && (
        <FormErrorMessage errors={validationErrors} />
      )}
      
      {/* Form fields */}
      
      <button 
        type="submit" 
        onClick={handleSubmit}
      >
        Submit
      </button>
    </div>
  );
};
```

**CSS for Error Messages:**

```css
.validation-message {
  margin-top: 0.25rem;
  font-size: 0.85rem;
  display: flex;
  align-items: flex-start;
}

.validation-message--error {
  color: #d32f2f;
}

.validation-message--warning {
  color: #f57c00;
}

.validation-message--info {
  color: #0288d1;
}

.validation-icon {
  margin-right: 0.5rem;
}

.form-validation-summary {
  background-color: #ffebee;
  border: 1px solid #ffcdd2;
  border-radius: 4px;
  padding: 1rem;
  margin-bottom: 1.5rem;
}

.validation-summary-title {
  color: #d32f2f;
  font-size: 1rem;
  margin-top: 0;
  margin-bottom: 0.5rem;
}

.validation-summary-list {
  margin: 0;
  padding-left: 1.5rem;
}

.validation-summary-item {
  margin-bottom: 0.25rem;
}

.validation-summary-item a {
  color: #d32f2f;
  text-decoration: underline;
}

.validation-summary-item a:hover {
  text-decoration: none;
}
```

**Testing Considerations:**

* Verify that error messages display correctly for different validation errors
* Test with screen readers to ensure accessibility
* Verify that error messages are properly associated with form fields
* Test form-level error summary functionality
* Ensure error messages are visually distinct and noticeable
* Test with various screen sizes to ensure responsive design
* Verify that error messages are cleared when errors are resolved
