### ISSUE TITLE
Ensure validation messages are accessible

### ISSUE THREAD

**Issue by Kneesal** [JesusFilm/core#5678]
**Objective:**
Ensure that all validation messages and error indicators are fully accessible to users with disabilities, including screen reader users and keyboard-only users.

**Requirements:**

* Implement proper ARIA attributes for validation messages
* Ensure validation errors are announced by screen readers
* Provide clear visual indicators that work with high contrast modes
* Support keyboard navigation to and from error messages
* Ensure error messages are perceivable by users with color blindness

**Implementation Details:**

* Add appropriate ARIA attributes to form fields and error messages
* Implement live regions for dynamic error messages
* Ensure proper focus management when errors occur
* Use both color and icons/text to indicate errors
* Test with various assistive technologies

**Technical Approach:**

```tsx
// Accessible error message component
const AccessibleErrorMessage: React.FC<ErrorMessageProps> = ({
  message,
  id,
  severity = 'error'
}) => {
  if (!message) return null;
  
  const className = `validation-message validation-message--${severity}`;
  
  return (
    <div 
      id={id}
      className={className}
      role="alert" // Announces the message when it appears
      aria-live="assertive" // Interrupts the screen reader to announce the message
    >
      {severity === 'error' && (
        <span className="validation-icon" aria-hidden="true">
          ⚠️
        </span>
      )}
      <span className="validation-text">{message}</span>
    </div>
  );
};

// Accessible form field with validation
const AccessibleTextInputBlock: React.FC<TextInputBlockProps> = ({ 
  block, 
  onChange,
  validationError,
  ...props 
}) => {
  const { 
    label, 
    placeholder, 
    fieldType = 'text',
    isRequired,
    // other props 
  } = block;
  
  const inputId = `text-input-${block.id}`;
  const errorId = `error-${block.id}`;
  
  // Determine if the field is in an error state
  const hasError = !!validationError;
  
  return (
    <div className={`text-input-block ${hasError ? 'text-input-block--error' : ''}`}>
      {label && (
        <label 
          htmlFor={inputId}
          className="text-input-label"
        >
          {label}
          {isRequired && (
            <span className="required-indicator" aria-hidden="true">*</span>
          )}
          {isRequired && (
            <span className="sr-only">(required)</span>
          )}
        </label>
      )}
      <input
        id={inputId}
        type={fieldType === 'email' ? 'email' : fieldType === 'phone' ? 'tel' : 'text'}
        placeholder={placeholder}
        required={isRequired}
        aria-required={isRequired}
        aria-invalid={hasError} // Indicates to screen readers that the field has an error
        aria-describedby={
          // Combine IDs of hint text and error message if both exist
          [
            block.hintText ? `hint-${block.id}` : null,
            hasError ? errorId : null
          ].filter(Boolean).join(' ') || undefined
        }
        // other props
      />
      {block.hintText && (
        <div 
          id={`hint-${block.id}`}
          className="text-input-hint"
        >
          {block.hintText}
        </div>
      )}
      {hasError && (
        <AccessibleErrorMessage
          id={errorId}
          message={validationError}
          severity="error"
        />
      )}
    </div>
  );
};

// Accessible form with error summary
const AccessibleForm: React.FC = () => {
  const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const errorSummaryRef = useRef<HTMLDivElement>(null);
  
  // Focus the error summary when validation errors occur
  useEffect(() => {
    if (validationErrors.length > 0 && errorSummaryRef.current) {
      errorSummaryRef.current.focus();
    }
  }, [validationErrors]);
  
  // Form implementation
  
  return (
    <div className="form-container">
      {validationErrors.length > 0 && (
        <div 
          ref={errorSummaryRef}
          className="form-validation-summary" 
          role="alert" 
          aria-live="assertive"
          tabIndex={-1} // Makes it focusable programmatically
        >
          <h3 className="validation-summary-title">
            Please correct the following {validationErrors.length === 1 ? 'error' : `${validationErrors.length} errors`}:
          </h3>
          <ul className="validation-summary-list">
            {validationErrors.map((error, index) => (
              <li key={index} className="validation-summary-item">
                <a 
                  href={`#text-input-${error.id}`}
                  onClick={(e) => {
                    e.preventDefault();
                    const element = document.getElementById(`text-input-${error.id}`);
                    if (element) {
                      element.focus();
                    }
                  }}
                >
                  {error.fieldName}: {error.errorMessage}
                </a>
              </li>
            ))}
          </ul>
        </div>
      )}
      
      {/* Form fields */}
      
      <button 
        type="submit" 
        onClick={handleSubmit}
        disabled={isSubmitting}
        aria-busy={isSubmitting}
      >
        {isSubmitting ? 'Submitting...' : 'Submit'}
      </button>
    </div>
  );
};
```

**Additional CSS for Accessibility:**

```css
/* Screen reader only class */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}

/* Ensure error states are perceivable without relying solely on color */
.text-input-block--error input {
  border-color: #d32f2f;
  border-width: 2px;
  box-shadow: 0 0 0 1px #d32f2f;
}

/* High contrast mode support */
@media (forced-colors: active) {
  .text-input-block--error input {
    outline: 2px solid CanvasText;
    outline-offset: 2px;
  }
  
  .validation-message--error {
    outline: 1px solid CanvasText;
    padding: 0.25rem;
  }
}

/* Focus styles for error summary */
.form-validation-summary:focus {
  outline: 2px solid #5e6ad2;
  outline-offset: 2px;
}
```

**Testing Considerations:**

* Test with screen readers (NVDA, JAWS, VoiceOver)
* Test with keyboard-only navigation
* Test with high contrast mode
* Test with color blindness simulators
* Verify that error messages are properly announced by screen readers
* Test focus management when errors occur
* Verify that error states are perceivable without relying solely on color
* Test with various assistive technologies and browser combinations
