### ISSUE TITLE
Create visual indicators for linked text blocks

### ISSUE THREAD

**Issue by Kneesal** [JesusFilm/core#5681]
**Objective:**
Create visual indicators for text blocks that are linked to text input fields to make the relationship clear to users and content creators.

**Requirements:**

* Add visual indicators to text blocks that are linked to text input fields
* Make the relationship between text blocks and input fields visually clear
* Ensure indicators are visible in both edit and view modes
* Maintain the visual design language of the application
* Ensure indicators are accessible and perceivable by all users

**Implementation Details:**

* Design and implement visual indicators for linked text blocks
* Add CSS styles for the indicators
* Ensure indicators are visible in both edit and view modes
* Implement hover states to highlight the relationship
* Ensure indicators are accessible to users with visual impairments

**Technical Approach:**

```tsx
// Updated TextBlock component with linked indicator
const TextBlock: React.FC<TextBlockProps> = ({ 
  block, 
  isLinkedToInput,
  linkedInputId,
  ...props 
}) => {
  const blockId = `text-block-${block.id}`;
  
  // Add classes based on whether the block is linked to an input
  const blockClasses = classNames(
    'text-block',
    { 'text-block--linked': isLinkedToInput }
  );
  
  return (
    <div 
      id={blockId}
      className={blockClasses}
      data-linked-input={isLinkedToInput ? linkedInputId : undefined}
    >
      <div className="text-block__content">
        {block.text}
      </div>
      
      {isLinkedToInput && (
        <div className="text-block__link-indicator" aria-hidden="true">
          <span className="text-block__link-icon">🔗</span>
          <span className="text-block__link-text">Linked to input field</span>
        </div>
      )}
    </div>
  );
};

// Updated TextInputBlock component with linked indicator
const TextInputBlock: React.FC<TextInputBlockProps> = ({ 
  block, 
  onChange,
  validationError,
  getBlockById,
  ...props 
}) => {
  const { 
    label,
    placeholder, 
    fieldType = 'text',
    isRequired,
    linkedTextBlockId,
    // other props 
  } = block;
  
  const inputId = `text-input-${block.id}`;
  
  // Add classes based on whether the block has a linked text block
  const blockClasses = classNames(
    'text-input-block',
    { 'text-input-block--linked': !!linkedTextBlockId }
  );
  
  return (
    <div className={blockClasses}>
      {/* Input implementation */}
      
      {linkedTextBlockId && (
        <div className="text-input-block__link-indicator" aria-hidden="true">
          <span className="text-input-block__link-icon">🔗</span>
          <span className="text-input-block__link-text">
            Linked to text block
          </span>
        </div>
      )}
    </div>
  );
};

// Page component that handles the linking
const PageComponent: React.FC = () => {
  // State to track linked blocks
  const [linkedBlocks, setLinkedBlocks] = useState<Record<string, string>>({});
  
  // Function to check if a text block is linked to an input
  const isTextBlockLinked = (blockId: string) => {
    return Object.values(linkedBlocks).includes(blockId);
  };
  
  // Function to get the input ID that a text block is linked to
  const getLinkedInputId = (blockId: string) => {
    const entry = Object.entries(linkedBlocks).find(([_, textBlockId]) => textBlockId === blockId);
    return entry ? entry[0] : undefined;
  };
  
  // Update linked blocks when a text input block is updated
  const handleTextInputBlockChange = (blockId: string, updatedBlock: TextInputBlockSchema) => {
    // Update the linkedBlocks state
    setLinkedBlocks(prev => {
      const newLinkedBlocks = { ...prev };
      
      // Remove old link if it exists
      if (prev[blockId] && prev[blockId] !== updatedBlock.linkedTextBlockId) {
        delete newLinkedBlocks[blockId];
      }
      
      // Add new link if it exists
      if (updatedBlock.linkedTextBlockId) {
        newLinkedBlocks[blockId] = updatedBlock.linkedTextBlockId;
      }
      
      return newLinkedBlocks;
    });
    
    // Other change handling logic
  };
  
  // Render blocks with appropriate props
  return (
    <div className="page-content">
      {blocks.map(block => {
        if (block.type === 'text') {
          return (
            <TextBlock
              key={block.id}
              block={block}
              isLinkedToInput={isTextBlockLinked(block.id)}
              linkedInputId={getLinkedInputId(block.id)}
            />
          );
        } else if (block.type === 'textInput') {
          return (
            <TextInputBlock
              key={block.id}
              block={block}
              onChange={(updatedBlock) => handleTextInputBlockChange(block.id, updatedBlock)}
              getBlockById={getBlockById}
            />
          );
        }
        // Other block types
      })}
    </div>
  );
};
```

**CSS for Visual Indicators:**

```css
/* Linked text block styles */
.text-block--linked {
  position: relative;
  border-left: 3px solid #5e6ad2;
  padding-left: 0.5rem;
}

.text-block__link-indicator {
  position: absolute;
  top: 0;
  right: 0;
  background-color: #5e6ad2;
  color: white;
  font-size: 0.75rem;
  padding: 0.25rem 0.5rem;
  border-radius: 0 0 0 4px;
  display: flex;
  align-items: center;
}

.text-block__link-icon {
  margin-right: 0.25rem;
}

/* Hover effect to show connection */
.text-block--linked:hover {
  background-color: rgba(94, 106, 210, 0.1);
}

/* Linked text input block styles */
.text-input-block--linked {
  position: relative;
  border-left: 3px solid #5e6ad2;
  padding-left: 0.5rem;
}

.text-input-block__link-indicator {
  position: absolute;
  top: 0;
  right: 0;
  background-color: #5e6ad2;
  color: white;
  font-size: 0.75rem;
  padding: 0.25rem 0.5rem;
  border-radius: 0 0 0 4px;
  display: flex;
  align-items: center;
}

.text-input-block__link-icon {
  margin-right: 0.25rem;
}

/* Hover effect to show connection */
.text-input-block--linked:hover {
  background-color: rgba(94, 106, 210, 0.1);
}

/* Edit mode styles */
.edit-mode .text-block--linked,
.edit-mode .text-input-block--linked {
  border-left-width: 5px;
}

.edit-mode .text-block__link-indicator,
.edit-mode .text-input-block__link-indicator {
  font-size: 0.85rem;
  padding: 0.35rem 0.75rem;
}
```

**Testing Considerations:**

* Verify that visual indicators are displayed correctly for linked text blocks
* Test with various screen sizes to ensure responsive design
* Ensure indicators are visible in both edit and view modes
* Test with high contrast mode to ensure visibility
* Verify that indicators are perceivable by users with color blindness
* Test hover states to ensure they work correctly
* Verify that indicators do not interfere with the content or functionality of the blocks
