### ISSUE TITLE
Add UI for text block selection

### ISSUE THREAD

**Issue by Kneesal** [JesusFilm/core#5683]
**Objective:**
Create a user-friendly UI for selecting text blocks to link to text input fields, making it easy for content creators to associate questions with answer fields.

**Requirements:**

* Create an intuitive UI for selecting text blocks to link to text input fields
* Display a list of available text blocks with previews
* Allow filtering or searching for text blocks
* Provide clear visual feedback for selected text blocks
* Support keyboard navigation and accessibility

**Implementation Details:**

* Design and implement a text block selector component
* Add UI for browsing and selecting text blocks
* Implement search/filter functionality for text blocks
* Create preview functionality to see text block content
* Ensure proper keyboard navigation and accessibility

**Technical Approach:**

```tsx
// Text block selector component with search and preview
const TextBlockSelector: React.FC<{
  selectedBlockId?: string;
  onSelect: (blockId: string | undefined) => void;
}> = ({ selectedBlockId, onSelect }) => {
  const [availableTextBlocks, setAvailableTextBlocks] = useState<TextBlock[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [previewBlockId, setPreviewBlockId] = useState<string | null>(null);
  
  // Fetch available text blocks on component mount
  useEffect(() => {
    const fetchTextBlocks = async () => {
      try {
        // API call to get text blocks from the current page/section
        const blocks = await getTextBlocksInCurrentSection();
        setAvailableTextBlocks(blocks);
      } catch (error) {
        console.error('Failed to fetch text blocks:', error);
      }
    };
    
    fetchTextBlocks();
  }, []);
  
  // Filter text blocks based on search query
  const filteredBlocks = useMemo(() => {
    if (!searchQuery.trim()) {
      return availableTextBlocks;
    }
    
    const query = searchQuery.toLowerCase();
    return availableTextBlocks.filter(block => 
      block.text.toLowerCase().includes(query)
    );
  }, [availableTextBlocks, searchQuery]);
  
  // Get the preview block
  const previewBlock = useMemo(() => {
    if (!previewBlockId) return null;
    return availableTextBlocks.find(block => block.id === previewBlockId) || null;
  }, [availableTextBlocks, previewBlockId]);
  
  // Handle keyboard navigation
  const handleKeyDown = (e: React.KeyboardEvent, blockId: string) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      onSelect(blockId);
    } else if (e.key === 'Escape') {
      e.preventDefault();
      setPreviewBlockId(null);
    }
  };
  
  return (
    <div className="text-block-selector">
      <div className="text-block-selector__header">
        <h3 className="text-block-selector__title">Select a text block to use as label</h3>
        <div className="text-block-selector__search">
          <input
            type="text"
            placeholder="Search text blocks..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            aria-label="Search text blocks"
          />
          {searchQuery && (
            <button
              className="text-block-selector__clear-search"
              onClick={() => setSearchQuery('')}
              aria-label="Clear search"
            >
              ✕
            </button>
          )}
        </div>
      </div>
      
      <div className="text-block-selector__content">
        <div className="text-block-selector__list">
          {filteredBlocks.length === 0 ? (
            <div className="text-block-selector__empty">
              No text blocks found. {searchQuery ? 'Try a different search term.' : ''}
            </div>
          ) : (
            <ul className="text-block-selector__items">
              <li className="text-block-selector__item">
                <button
                  className={classNames(
                    'text-block-selector__item-button',
                    { 'text-block-selector__item-button--selected': !selectedBlockId }
                  )}
                  onClick={() => onSelect(undefined)}
                >
                  <span className="text-block-selector__item-icon">✏️</span>
                  <span className="text-block-selector__item-text">Custom label (no text block)</span>
                </button>
              </li>
              {filteredBlocks.map(block => (
                <li key={block.id} className="text-block-selector__item">
                  <button
                    className={classNames(
                      'text-block-selector__item-button',
                      { 'text-block-selector__item-button--selected': selectedBlockId === block.id }
                    )}
                    onClick={() => onSelect(block.id)}
                    onMouseEnter={() => setPreviewBlockId(block.id)}
                    onMouseLeave={() => setPreviewBlockId(null)}
                    onFocus={() => setPreviewBlockId(block.id)}
                    onBlur={() => setPreviewBlockId(null)}
                    onKeyDown={(e) => handleKeyDown(e, block.id)}
                  >
                    <span className="text-block-selector__item-icon">📄</span>
                    <span className="text-block-selector__item-text">
                      {block.text.length > 50 
                        ? `${block.text.substring(0, 50)}...` 
                        : block.text}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
        
        {previewBlock && (
          <div className="text-block-selector__preview">
            <h4 className="text-block-selector__preview-title">Preview</h4>
            <div className="text-block-selector__preview-content">
              {previewBlock.text}
            </div>
            <div className="text-block-selector__preview-actions">
              <button
                className="text-block-selector__preview-select"
                onClick={() => onSelect(previewBlock.id)}
              >
                Select this text block
              </button>
            </div>
          </div>
        )}
      </div>
      
      <div className="text-block-selector__footer">
        <button
          className="text-block-selector__cancel"
          onClick={() => onSelect(selectedBlockId)}
        >
          Cancel
        </button>
        {selectedBlockId && (
          <button
            className="text-block-selector__clear"
            onClick={() => onSelect(undefined)}
          >
            Clear selection
          </button>
        )}
      </div>
    </div>
  );
};

// Usage in TextInputBlock editor
const TextInputBlockEditor: React.FC<TextInputBlockEditorProps> = ({
  block,
  onChange,
  // other props
}) => {
  const [showSelector, setShowSelector] = useState(false);
  
  const handleLinkedTextBlockChange = (blockId: string | undefined) => {
    onChange({
      ...block,
      linkedTextBlockId: blockId,
      // If a text block is selected, clear the custom label
      label: blockId ? '' : block.label
    });
    setShowSelector(false);
  };
  
  return (
    <div className="text-input-block-editor">
      <div className="form-group">
        <label className="form-label">Label</label>
        <div className="text-input-block-editor__label-options">
          {block.linkedTextBlockId ? (
            <div className="text-input-block-editor__linked-block">
              <span className="text-input-block-editor__linked-icon">🔗</span>
              <span className="text-input-block-editor__linked-text">
                Using text block as label
              </span>
              <button
                className="text-input-block-editor__change-link"
                onClick={() => setShowSelector(true)}
              >
                Change
              </button>
              <button
                className="text-input-block-editor__remove-link"
                onClick={() => handleLinkedTextBlockChange(undefined)}
              >
                Remove
              </button>
            </div>
          ) : (
            <>
              <input
                type="text"
                value={block.label || ''}
                onChange={(e) => onChange({ ...block, label: e.target.value })}
                placeholder="Enter label text"
              />
              <button
                className="text-input-block-editor__use-text-block"
                onClick={() => setShowSelector(true)}
              >
                Use text block
              </button>
            </>
          )}
        </div>
      </div>
      
      {/* Other editor fields */}
      
      {showSelector && (
        <div className="text-input-block-editor__selector-modal">
          <div className="text-input-block-editor__selector-backdrop" onClick={() => setShowSelector(false)} />
          <div className="text-input-block-editor__selector-container">
            <TextBlockSelector
              selectedBlockId={block.linkedTextBlockId}
              onSelect={handleLinkedTextBlockChange}
            />
          </div>
        </div>
      )}
    </div>
  );
};
```

**CSS for Text Block Selector:**

```css
.text-block-selector {
  background-color: white;
  border-radius: 4px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  display: flex;
  flex-direction: column;
  max-height: 80vh;
  width: 100%;
  max-width: 600px;
}

.text-block-selector__header {
  border-bottom: 1px solid #e0e0e0;
  padding: 1rem;
}

.text-block-selector__title {
  font-size: 1.25rem;
  margin: 0 0 1rem 0;
}

.text-block-selector__search {
  position: relative;
}

.text-block-selector__search input {
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  font-size: 1rem;
  padding: 0.5rem;
  width: 100%;
}

.text-block-selector__clear-search {
  background: none;
  border: none;
  color: #999;
  cursor: pointer;
  font-size: 1rem;
  position: absolute;
  right: 0.5rem;
  top: 50%;
  transform: translateY(-50%);
}

.text-block-selector__content {
  display: flex;
  flex: 1;
  min-height: 300px;
  overflow: hidden;
}

.text-block-selector__list {
  border-right: 1px solid #e0e0e0;
  flex: 1;
  overflow-y: auto;
  padding: 1rem;
}

.text-block-selector__items {
  list-style: none;
  margin: 0;
  padding: 0;
}

.text-block-selector__item {
  margin-bottom: 0.5rem;
}

.text-block-selector__item-button {
  align-items: center;
  background: none;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  cursor: pointer;
  display: flex;
  font-size: 1rem;
  padding: 0.75rem;
  text-align: left;
  width: 100%;
}

.text-block-selector__item-button:hover,
.text-block-selector__item-button:focus {
  background-color: #f5f5f5;
  outline: none;
}

.text-block-selector__item-button--selected {
  background-color: #e8f0fe;
  border-color: #5e6ad2;
}

.text-block-selector__item-icon {
  margin-right: 0.5rem;
}

.text-block-selector__preview {
  flex: 1;
  padding: 1rem;
}

.text-block-selector__preview-title {
  font-size: 1rem;
  margin: 0 0 1rem 0;
}

.text-block-selector__preview-content {
  background-color: #f5f5f5;
  border-radius: 4px;
  max-height: 200px;
  overflow-y: auto;
  padding: 1rem;
}

.text-block-selector__preview-actions {
  margin-top: 1rem;
  text-align: right;
}

.text-block-selector__footer {
  border-top: 1px solid #e0e0e0;
  display: flex;
  justify-content: flex-end;
  padding: 1rem;
}

.text-block-selector__cancel,
.text-block-selector__clear {
  background: none;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
  margin-left: 0.5rem;
  padding: 0.5rem 1rem;
}

.text-block-selector__clear {
  color: #d32f2f;
}

/* Modal styles */
.text-input-block-editor__selector-modal {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 1000;
  display: flex;
  align-items: center;
  justify-content: center;
}

.text-input-block-editor__selector-backdrop {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
}

.text-input-block-editor__selector-container {
  position: relative;
  z-index: 1001;
  width: 90%;
  max-width: 800px;
}
```

**Testing Considerations:**

* Verify that the text block selector UI is intuitive and easy to use
* Test search/filter functionality with various search terms
* Ensure preview functionality works correctly
* Test keyboard navigation and accessibility
* Verify that selected text blocks are properly linked to input fields
* Test with various screen sizes to ensure responsive design
* Verify that the UI works correctly in different browsers
